### Sort

In [0]:
%run "./0. dataFrame"

In [0]:
df.show(5)

+-----------+-------------+--------------------+----------+----+-----------+------------+-------------------+
|amount_paid|customer_from|               email|first_name|  id|is_customer|   last_name|    last_updated_ts|
+-----------+-------------+--------------------+----------+----+-----------+------------+-------------------+
|    1000.55|   2021-01-15|cvandenoord0@etsy...|    Corrie|   1|       true|Van den Oord|2021-02-10 01:15:00|
|       null|         null|                null|      null|null|       null|        null|               null|
|      900.0|   2021-02-14|nbrewitt1@dailyma...|  Nikolaus|   2|       true|     Brewitt|2021-02-18 03:33:00|
|     850.55|   2021-01-21|openney2@vistapri...|    Orelie|   3|       true|      Penney|2021-03-15 15:16:55|
|     850.55|   2021-01-21|openney2@vistapri...|    Orelie|   3|       true|      Penney|2021-03-15 15:16:55|
+-----------+-------------+--------------------+----------+----+-----------+------------+-------------------+
only showing top 5 rows

In [0]:
df.sort('email').show() #By-default: Ascending

+-----------+-------------+--------------------+----------+----+-----------+------------+-------------------+
|amount_paid|customer_from|               email|first_name|  id|is_customer|   last_name|    last_updated_ts|
+-----------+-------------+--------------------+----------+----+-----------+------------+-------------------+
|       null|         null|                null|      null|null|       null|        null|               null|
|       null|         null|                null|      null|null|       null|        null|               null|
|       null|         null|                null|      null|   5|       null|        null|               null|
|       null|         null|                null|      Kurt|null|      false|        Rome|2021-04-02 00:55:18|
|       null|         null|  amaddocks3@home.pl|     Ashby|   4|      false|    Maddocks|2021-04-10 17:45:30|
|       null|         null|  amaddocks3@home.pl|     Ashby|   4|      false|    Maddocks|2021-04-10 17:45:30|
|    1000.55|   2021-01-15|cvandenoord0@etsy...|    Corrie|   1|       true|Van den Oord|2021-02-10 01:15:00|
|       null|         null|krome4@shutterfly...|      Kurt|   5|      false|        Rome|2021-04-02 00:55:18|
|       null|         null|nbrewitt1@dailyma...|      null|null|       null|        null|               null|
|      900.0|   2021-02-14|nbrewitt1@dailyma...|  Nikolaus|   2|       true|     Brewitt|2021-02-18 03:33:00|
|     1050.0|   2021-02-14|nbrewitt1@dailyma...|  Nikolaus|   2|       true|     Brewitt|2021-02-25 03:33:00|
|     850.55|   2021-01-21|openney2@vistapri...|    Orelie|   3|       true|      Penney|2021-03-15 15:16:55|
|     850.55|   2021-01-21|openney2@vistapri...|    Orelie|   3|       true|      Penney|2021-03-15 15:16:55|
+-----------+-------------+--------------------+----------+----+-----------+------------+-------------------+

In [0]:
df.sort(df.email.desc()).show() #Descending

+-----------+-------------+--------------------+----------+----+-----------+------------+-------------------+
|amount_paid|customer_from|               email|first_name|  id|is_customer|   last_name|    last_updated_ts|
+-----------+-------------+--------------------+----------+----+-----------+------------+-------------------+
|     850.55|   2021-01-21|openney2@vistapri...|    Orelie|   3|       true|      Penney|2021-03-15 15:16:55|
|     850.55|   2021-01-21|openney2@vistapri...|    Orelie|   3|       true|      Penney|2021-03-15 15:16:55|
|       null|         null|nbrewitt1@dailyma...|      null|null|       null|        null|               null|
|      900.0|   2021-02-14|nbrewitt1@dailyma...|  Nikolaus|   2|       true|     Brewitt|2021-02-18 03:33:00|
|     1050.0|   2021-02-14|nbrewitt1@dailyma...|  Nikolaus|   2|       true|     Brewitt|2021-02-25 03:33:00|
|       null|         null|krome4@shutterfly...|      Kurt|   5|      false|        Rome|2021-04-02 00:55:18|
|    1000.55|   2021-01-15|cvandenoord0@etsy...|    Corrie|   1|       true|Van den Oord|2021-02-10 01:15:00|
|       null|         null|  amaddocks3@home.pl|     Ashby|   4|      false|    Maddocks|2021-04-10 17:45:30|
|       null|         null|  amaddocks3@home.pl|     Ashby|   4|      false|    Maddocks|2021-04-10 17:45:30|
|       null|         null|                null|      null|null|       null|        null|               null|
|       null|         null|                null|      null|   5|       null|        null|               null|
|       null|         null|                null|      null|null|       null|        null|               null|
|       null|         null|                null|      Kurt|null|      false|        Rome|2021-04-02 00:55:18|
+-----------+-------------+--------------------+----------+----+-----------+------------+-------------------+

In [0]:
df.sort(df.email.asc_nulls_last()).show() #This way we can sort with ascending keeping nulls at last or first

+-----------+-------------+--------------------+----------+----+-----------+------------+-------------------+
|amount_paid|customer_from|               email|first_name|  id|is_customer|   last_name|    last_updated_ts|
+-----------+-------------+--------------------+----------+----+-----------+------------+-------------------+
|       null|         null|  amaddocks3@home.pl|     Ashby|   4|      false|    Maddocks|2021-04-10 17:45:30|
|       null|         null|  amaddocks3@home.pl|     Ashby|   4|      false|    Maddocks|2021-04-10 17:45:30|
|    1000.55|   2021-01-15|cvandenoord0@etsy...|    Corrie|   1|       true|Van den Oord|2021-02-10 01:15:00|
|       null|         null|krome4@shutterfly...|      Kurt|   5|      false|        Rome|2021-04-02 00:55:18|
|       null|         null|nbrewitt1@dailyma...|      null|null|       null|        null|               null|
|      900.0|   2021-02-14|nbrewitt1@dailyma...|  Nikolaus|   2|       true|     Brewitt|2021-02-18 03:33:00|
|     1050.0|   2021-02-14|nbrewitt1@dailyma...|  Nikolaus|   2|       true|     Brewitt|2021-02-25 03:33:00|
|     850.55|   2021-01-21|openney2@vistapri...|    Orelie|   3|       true|      Penney|2021-03-15 15:16:55|
|     850.55|   2021-01-21|openney2@vistapri...|    Orelie|   3|       true|      Penney|2021-03-15 15:16:55|
|       null|         null|                null|      null|null|       null|        null|               null|
|       null|         null|                null|      null|   5|       null|        null|               null|
|       null|         null|                null|      null|null|       null|        null|               null|
|       null|         null|                null|      Kurt|null|      false|        Rome|2021-04-02 00:55:18|
+-----------+-------------+--------------------+----------+----+-----------+------------+-------------------+

>Composite Sorting

In [0]:
df.sort('email','id',ascending = [0,0]).show() #This way to control multi-column sort and asc/desc when giving strings as input

+-----------+-------------+--------------------+----------+----+-----------+------------+-------------------+
|amount_paid|customer_from|               email|first_name|  id|is_customer|   last_name|    last_updated_ts|
+-----------+-------------+--------------------+----------+----+-----------+------------+-------------------+
|     850.55|   2021-01-21|openney2@vistapri...|    Orelie|   3|       true|      Penney|2021-03-15 15:16:55|
|     850.55|   2021-01-21|openney2@vistapri...|    Orelie|   3|       true|      Penney|2021-03-15 15:16:55|
|     1050.0|   2021-02-14|nbrewitt1@dailyma...|  Nikolaus|   2|       true|     Brewitt|2021-02-25 03:33:00|
|      900.0|   2021-02-14|nbrewitt1@dailyma...|  Nikolaus|   2|       true|     Brewitt|2021-02-18 03:33:00|
|       null|         null|nbrewitt1@dailyma...|      null|null|       null|        null|               null|
|       null|         null|krome4@shutterfly...|      Kurt|   5|      false|        Rome|2021-04-02 00:55:18|
|    1000.55|   2021-01-15|cvandenoord0@etsy...|    Corrie|   1|       true|Van den Oord|2021-02-10 01:15:00|
|       null|         null|  amaddocks3@home.pl|     Ashby|   4|      false|    Maddocks|2021-04-10 17:45:30|
|       null|         null|  amaddocks3@home.pl|     Ashby|   4|      false|    Maddocks|2021-04-10 17:45:30|
|       null|         null|                null|      null|   5|       null|        null|               null|
|       null|         null|                null|      null|null|       null|        null|               null|
|       null|         null|                null|      Kurt|null|      false|        Rome|2021-04-02 00:55:18|
|       null|         null|                null|      null|null|       null|        null|               null|
+-----------+-------------+--------------------+----------+----+-----------+------------+-------------------+

### Aggregate

The common aggregate functions that are available as part of `pyspark.sql.functions`
* `count, sum, min, max, and avg`

In [0]:
from pyspark.sql.functions import *
orders = spark.read.json('/public/retail_db_json/orders')
order_items = spark.read.json('/public/retail_db_json/order_items')

In [0]:
orders.groupBy('order_status').agg(count("*")).show() #This is to count by Group
orders.select(count('*')).show() #To get the count of Rows, OR
orders.count() #To get the count of Rows

+---------------+--------+
|   order_status|count(1)|
+---------------+--------+
|PENDING_PAYMENT|   15030|
|       COMPLETE|   22899|
|        ON_HOLD|    3798|
| PAYMENT_REVIEW|     729|
|     PROCESSING|    8275|
|         CLOSED|    7556|
|SUSPECTED_FRAUD|    1558|
|        PENDING|    7610|
|       CANCELED|    1428|
+---------------+--------+

+--------+
|count(1)|
+--------+
|   68883|
+--------+

Out[15]: 68883

In [0]:
order_items.show(5)
order_items.filter('order_item_order_id = 2').select(sum("order_item_subtotal")).show() #This is to sum all on filter

+-------------+-------------------+---------------------+------------------------+-------------------+-------------------+
|order_item_id|order_item_order_id|order_item_product_id|order_item_product_price|order_item_quantity|order_item_subtotal|
+-------------+-------------------+---------------------+------------------------+-------------------+-------------------+
|            1|                  1|                  957|                  299.98|                  1|             299.98|
|            2|                  2|                 1073|                  199.99|                  1|             199.99|
|            3|                  2|                  502|                    50.0|                  5|              250.0|
|            4|                  2|                  403|                  129.99|                  1|             129.99|
|            5|                  4|                  897|                   24.99|                  2|              49.98|
+-------------+-------------------+---------------------+------------------------+-------------------+-------------------+
only showing top 5 rows

+------------------------+
|sum(order_item_subtotal)|
+------------------------+
|                  579.98|
+------------------------+

In [0]:
orders.groupBy().min().show()
orders.groupBy().max().show()
orders.groupBy().avg().show()

+----------------------+-------------+
|min(order_customer_id)|min(order_id)|
+----------------------+-------------+
|                     1|            1|
+----------------------+-------------+

+----------------------+-------------+
|max(order_customer_id)|max(order_id)|
+----------------------+-------------+
|                 12435|        68883|
+----------------------+-------------+

+----------------------+-------------+
|avg(order_customer_id)|avg(order_id)|
+----------------------+-------------+
|     6216.571098819738|      34442.0|
+----------------------+-------------+

In [0]:
order_items. \
    filter('order_item_order_id = 2'). \
    agg(
        count('order_item_quantity').alias('order_item_count'),
        sum('order_item_quantity').alias('order_quantity'),
        max('order_item_product_price').alias('item_price_max'),
        min('order_item_product_price').alias('item_price_min'),
        avg('order_item_product_price').alias('item_price_avg')
    ). \
    show()

+----------------+--------------+--------------+--------------+------------------+
|order_item_count|order_quantity|item_price_max|item_price_min|    item_price_avg|
+----------------+--------------+--------------+--------------+------------------+
|               3|             7|        199.99|          50.0|126.66000000000001|
+----------------+--------------+--------------+--------------+------------------+

### Join

In [0]:
%run "./0.a. dataframe to join"

+---------+----------------+-------------------+---------+-------------------+
|course_id|    course_title|course_published_dt|is_active|    last_updated_ts|
+---------+----------------+-------------------+---------+-------------------+
|        1|Mastering Python|         2021-01-14|     true|2021-02-18 16:57:25|
+---------+----------------+-------------------+---------+-------------------+
only showing top 1 row

+-------+---------------+--------------+----------------+
|user_id|user_first_name|user_last_name|      user_email|
+-------+---------------+--------------+----------------+
|      1|         Sandra|        Karpov|skarpov0@ovh.net|
+-------+---------------+--------------+----------------+
only showing top 1 row

+-------------------+-------+---------+----------+
|course_enrolment_id|user_id|course_id|price_paid|
+-------------------+-------+---------+----------+
|                  1|     10|        2|      9.99|
+-------------------+-------+---------+----------+
only showing top 1 row

In [0]:
help(courses_df.join)

Help on method join in module pyspark.sql.dataframe:

join(other: 'DataFrame', on: Union[str, List[str], pyspark.sql.column.Column, List[pyspark.sql.column.Column], NoneType] = None, how: Optional[str] = None) -> 'DataFrame' method of pyspark.sql.dataframe.DataFrame instance
    Joins with another :class:`DataFrame`, using the given join expression.

    .. versionadded:: 1.3.0

    Parameters
    ----------
    other : :class:`DataFrame`
        Right side of the join
    on : str, list or :class:`Column`, optional
        a string for the join column name, a list of column names,
        a join expression (Column), or a list of Columns.
        If `on` is a string or a list of strings indicating the name of the join column(s),
        the column(s) must exist on both sides, and this performs an equi-join.
    how : str, optional
        default ``inner``. Must be one of: ``inner``, ``cross``, ``outer``,
        ``full``, ``fullouter``, ``full_outer``, ``left``, ``leftouter``, ``left_outer``,
        ``right``, ``rightouter``, ``right_outer``, ``semi``, ``leftsemi``, ``left_semi``,
        ``anti``, ``leftanti`` and ``left_anti``.

    Examples
    --------
    The following performs a full outer join between ``df1`` and ``df2``.

    >>> from pyspark.sql.functions import desc
    >>> df.join(df2, df.name == df2.name, 'outer').select(df.name, df2.height)                 .sort(desc("name")).collect()
    [Row(name='Bob', height=85), Row(name='Alice', height=None), Row(name=None, height=80)]

    >>> df.join(df2, 'name', 'outer').select('name', 'height').sort(desc("name")).collect()
    [Row(name='Tom', height=80), Row(name='Bob', height=85), Row(name='Alice', height=None)]

    >>> cond = [df.name == df3.name, df.age == df3.age]
    >>> df.join(df3, cond, 'outer').select(df.name, df3.age).collect()
    [Row(name='Alice', age=2), Row(name='Bob', age=5)]

    >>> df.join(df2, 'name').select(df.name, df2.height).collect()
    [Row(name='Bob', height=85)]

    >>> df.join(df4, ['name', 'age']).select(df.name, df.age).collect()
    [Row(name='Bob', age=5)]

In [0]:
users_df.join(course_enrolments_df, users_df.user_id == course_enrolments_df.user_id).show()

+-------+---------------+--------------+--------------------+-------------------+-------+---------+----------+
|user_id|user_first_name|user_last_name|          user_email|course_enrolment_id|user_id|course_id|price_paid|
+-------+---------------+--------------+--------------------+-------------------+-------+---------+----------+
|      3|         Joanna|      Spennock|jspennock2@redcro...|                 10|      3|        3|     10.99|
|      3|         Joanna|      Spennock|jspennock2@redcro...|                 12|      3|        2|      9.99|
|      4|         Hirsch|       Conaboy|hconaboy3@barnesa...|                  7|      4|        5|     10.99|
|      4|         Hirsch|       Conaboy|hconaboy3@barnesa...|                 14|      4|        3|     10.99|
|      5|         Loreen|         Malin|lmalin4@independe...|                  2|      5|        2|      9.99|
|      5|         Loreen|         Malin|lmalin4@independe...|                  6|      5|        5|     10.99|
|      5|         Loreen|         Malin|lmalin4@independe...|                 13|      5|        2|      9.99|
|      7|         Trudey|       Choupin|     tchoupin6@de.vu|                  3|      7|        5|     10.99|
|      7|         Trudey|       Choupin|     tchoupin6@de.vu|                  8|      7|        3|     10.99|
|      7|         Trudey|       Choupin|     tchoupin6@de.vu|                 11|      7|        5|     10.99|
|      8|         Nadine|     Grimsdell|ngrimsdell7@sohu.com|                  5|      8|        2|      9.99|
|      8|         Nadine|     Grimsdell|ngrimsdell7@sohu.com|                  9|      8|        5|     10.99|
|      8|         Nadine|     Grimsdell|ngrimsdell7@sohu.com|                 15|      8|        2|      9.99|
|      9|        Vassily|         Tamas|vtamas8@businessw...|                  4|      9|        2|      9.99|
|     10|          Wells|      Simpkins|wsimpkins9@amazon...|                  1|     10|        2|      9.99|
+-------+---------------+--------------+--------------------+-------------------+-------+---------+----------+

In [0]:
# Get all columns from users_df and course_id as well as course_enrolment_id from course_enrolments
users_df. \
    join(course_enrolments_df, users_df.user_id == course_enrolments_df.user_id). \
    select(users_df['*'], course_enrolments_df['course_id'], course_enrolments_df['course_enrolment_id']). \
    show(2)

+-------+---------------+--------------+--------------------+---------+-------------------+
|user_id|user_first_name|user_last_name|          user_email|course_id|course_enrolment_id|
+-------+---------------+--------------+--------------------+---------+-------------------+
|      3|         Joanna|      Spennock|jspennock2@redcro...|        3|                 10|
|      3|         Joanna|      Spennock|jspennock2@redcro...|        2|                 12|
+-------+---------------+--------------+--------------------+---------+-------------------+
only showing top 2 rows

In [0]:
# left or left_outer or leftouter are same.

users_df.join(course_enrolments_df, users_df.user_id == course_enrolments_df.user_id, 'left_outer').show(2)

+-------+---------------+--------------+--------------------+-------------------+-------+---------+----------+
|user_id|user_first_name|user_last_name|          user_email|course_enrolment_id|user_id|course_id|price_paid|
+-------+---------------+--------------+--------------------+-------------------+-------+---------+----------+
|      1|         Sandra|        Karpov|    skarpov0@ovh.net|               null|   null|     null|      null|
|      2|           Kari|        Dearth|kdearth1@so-net.n...|               null|   null|     null|      null|
+-------+---------------+--------------+--------------------+-------------------+-------+---------+----------+
only showing top 2 rows

In [0]:
# outer or full or fullouter or full_outer are same

users_df.join(course_enrolments_df, users_df.user_id == course_enrolments_df.user_id, 'full').show(2)

+-------+---------------+--------------+--------------------+-------------------+-------+---------+----------+
|user_id|user_first_name|user_last_name|          user_email|course_enrolment_id|user_id|course_id|price_paid|
+-------+---------------+--------------+--------------------+-------------------+-------+---------+----------+
|      1|         Sandra|        Karpov|    skarpov0@ovh.net|               null|   null|     null|      null|
|      2|           Kari|        Dearth|kdearth1@so-net.n...|               null|   null|     null|      null|
+-------+---------------+--------------+--------------------+-------------------+-------+---------+----------+
only showing top 2 rows

**Overview of Broadcast Join in Spark**


* It is also known as *`map side as well as replicated join.`*
* The smaller data set will be broadcasted to all the executors in the cluster.
* The size of the smaller data set is driven by `spark.sql.autoBroadcastJoinThreshold`.
* We can even perform broadcast join when the smaller data set size is greater than `spark.sql.autoBroadcastJoinThreshold` by using `broadcast` function from `pyspark.sql.functions`.
* We can disable broadcast join by setting `spark.sql.autoBroadcastJoinThreshold` value to 0.
* If broadcast join is disabled then it will result in reduce side join.
* Make sure to setup multinode cluster using 28 GB Memory, 4 Cores each. Configure scaling between 2 and 4 nodes. Driver can be of minimum configuration.

In [0]:
# Default size is 10 MB.
spark.conf.get('spark.sql.autoBroadcastJoinThreshold')

Out[35]: '10485760b'

In [0]:
# We can disable broadcast join using this approach
spark.conf.set('spark.sql.autoBroadcastJoinThreshold', '0')

In [0]:
# Resetting to original value
spark.conf.set('spark.sql.autoBroadcastJoinThreshold', '10485760b')

In [0]:
# 1+ GB Data Set
clickstream = spark.read.csv('dbfs:/databricks-datasets/wikipedia-datasets/data-001/clickstream/raw-uncompressed/', sep='\t', header=True)

In [0]:
# 10+ GB Data Set
articles = spark.read.parquet('dbfs:/databricks-datasets/wikipedia-datasets/data-001/en_wikipedia/articles-only-parquet/')

In [0]:
%%time

# Default will be reduce side join as the size of smaller data set is more than 10 MB (default broadcast size)
clickstream.join(articles, articles.id == clickstream.curr_id).count()

In [0]:
from pyspark.sql.functions import broadcast

In [0]:
%%time
# We can use broadcast function to override existing broadcast join threshold
# We can also override by using this code spark.conf.set('spark.sql.autoBroadcastJoinThreshold', '1500m')
broadcast(clickstream).join(articles, articles.id == clickstream.curr_id).count()